// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Routine.Api.Data;

namespace Routine.Api.Migrations
{
    [DbContext(typeof(RoutineDbContext))]
    partial class RoutineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Routine.Api.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Introduction")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b6ff3aa-d91d-4086-baea-5ec3564a31be"),
                            Introduction = "Greate Company",
                            Name = "Microsoft"
                        },
                        new
                        {
                            Id = new Guid("beeba841-f929-4f56-bfef-644bbc0e58d7"),
                            Introduction = "Don't be evil ",
                            Name = "Google"
                        },
                        new
                        {
                            Id = new Guid("9a2193e3-2c2d-4625-b346-fbc5e789f0ad"),
                            Introduction = "Fubao Company",
                            Name = "Alipapa"
                        });
                });

            modelBuilder.Entity("Routine.Api.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3e3b794c-b675-4aac-b400-a43ffb9b78f4"),
                            CompanyId = new Guid("9b6ff3aa-d91d-4086-baea-5ec3564a31be"),
                            DateOfBirth = new DateTime(1976, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "MSFT231",
                            FirstName = "Nick",
                            Gender = 1,
                            LastName = "Carter"
                        },
                        new
                        {
                            Id = new Guid("b54d6ea3-55df-4708-8b6e-940c985a27d6"),
                            CompanyId = new Guid("9b6ff3aa-d91d-4086-baea-5ec3564a31be"),
                            DateOfBirth = new DateTime(1998, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "MSFT001",
                            FirstName = "Lisa",
                            Gender = 2,
                            LastName = "Jame"
                        },
                        new
                        {
                            Id = new Guid("b5681ff7-50fa-438c-a92e-5f8c49152238"),
                            CompanyId = new Guid("beeba841-f929-4f56-bfef-644bbc0e58d7"),
                            DateOfBirth = new DateTime(1988, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "G001",
                            FirstName = "Dick",
                            Gender = 1,
                            LastName = "Harden"
                        },
                        new
                        {
                            Id = new Guid("65182599-9944-4185-a8ad-eed47025cd7a"),
                            CompanyId = new Guid("9a2193e3-2c2d-4625-b346-fbc5e789f0ad"),
                            DateOfBirth = new DateTime(1982, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "A001",
                            FirstName = "马",
                            Gender = 1,
                            LastName = "云"
                        },
                        new
                        {
                            Id = new Guid("1b2a0599-788e-4898-a3b0-33cac2c397ea"),
                            CompanyId = new Guid("9a2193e3-2c2d-4625-b346-fbc5e789f0ad"),
                            DateOfBirth = new DateTime(1986, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "A002",
                            FirstName = "王",
                            Gender = 2,
                            LastName = "尼玛"
                        });
                });

            modelBuilder.Entity("Routine.Api.Entities.Employee", b =>
                {
                    b.HasOne("Routine.Api.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
